### ISSUE TITLE
Consistent TF_VAR_openshift_version for both Account role creation and cluster creation operations

### ISSUE THREAD

**Issue by bchandra-ocp** [terraform-redhat/terraform-provider-rhcs#243] opened 2023-08-17 03:03 UTC
Account Role creation operation requires TF_VAR_openshift_version set to x.y version e.g., 4.13
Cluster creation operation requires TF_VAR_openshift_version set to x.y.z version e.g., 4.13.5

Can the use set this once x.y.z and have both operations run together?

**Comment by tshefi** [comment] 2023-08-17 13:35
As you mentioned the first iteration of  TF_VAR_openshift_version uses x.y while the later uses x.y.z, if you fail to accommodate for this you'll get the error pasted at the end of the comment.  

Thus I tweaked Account Role's version to:
_rosa_openshift_version = join(".", slice(split(".", var.openshift_version), 0, 2))_
With this change Account Role & cluster creation completed as expected.  

Added the account role creation code on cluster create main.tf, attaching my config files.  
[main.tf.txt](https://github.com/terraform-redhat/terraform-provider-rhcs/files/12369934/main.tf.txt)
[terraform.tfvars.txt](https://github.com/terraform-redhat/terraform-provider-rhcs/files/12369936/terraform.tfvars.txt)
[variables.tf.txt](https://github.com/terraform-redhat/terraform-provider-rhcs/files/12369937/variables.tf.txt)


```
╷
│ Error: Resource precondition failed
│ 
│   on .terraform/modules/create_account_roles/main.tf line 55, in resource "null_resource" "validate_openshift_version":
│   55:       condition     = contains(local.minor_version_list, var.rosa_openshift_version)
│     ├────────────────
│     │ local.minor_version_list is list of string with 7 elements
│     │ var.rosa_openshift_version is "4.13.7"
│ 
│ ERROR: Expected a valid OpenShift versi

on. Valid versions: 4.10, 4.11, 4.12, 4.13, 4.14, 4.7, 4.8
╵
```

**Comment by tshefi** [comment] 2023-08-17 15:24
Oh one more thing to note, I later ran terraform destroy on same cluster, which led to a a problem probably caused by incorrect resource deletion order. Tread with caution on the road less traveled. 

```
module.oidc_config.rhcs_rosa_oidc_config.oidc_config: Destroying... [id=25lsfectbkh6s0r9kdong1e60qp8rd81]
╷
│ Warning: Cluster wasn't deleted yet
│ 
│ The cluster with identifier '25lsfqkj3ue77tf9k4ks88djbp2ujuht' is not
│ deleted yet, but the polling finisehd due to a timeout
╵
╷
│ Error: here are clusters using OIDC config, can't delete the configuration
│ 
│ here are clusters using OIDC config
│ 'https://d3gt1gce2zmg3d.cloudfront.net/25lsfectbkh6s0r9kdong1e60qp8rd81',
│ can't delete the configuration
╵

```

**Comment by nirarg** [comment] 2024-04-07 07:55
Hi @bchandra-ocp ,

The issue has already been resolved in the new [rosa-classic module](https://registry.terraform.io/modules/terraform-redhat/rosa-classic/rhcs/latest).
Within the module, you'll find all the sub-modules used to create classic clusters, along with multiple examples demonstrating how to create them for various scenarios.
I'm closing this issue now. If you have any further questions or concerns, please feel free to open a new issue.

**Closed by nirarg** 2024-04-07 07:55 UTC
